schema_version: 1
name: lekiwi_handeye_realsense_grasp_lidar_sound_following
robot_name: lekiwi_handeye_realsense_grasp_lidar
enabled_skills:
- name: act_cute
  implementation: so101_arm_v1
  planner_visible: true
- name: celebrate
  implementation: so101_arm_v1
  planner_visible: true
- name: resolve_object_pose
  implementation: lekiwi_navigation_v2
  planner_visible: true
- name: close_gripper_skill
  implementation: lekiwi_handeye_realsense_grasp
  planner_visible: true
- name: inspect_scene
  implementation: lekiwi_handeye_realsense_grasp
  planner_visible: true
- name: move_relative_ee
  implementation: lekiwi_handeye_realsense_grasp
  planner_visible: true
- name: open_gripper_skill
  implementation: lekiwi_handeye_realsense_grasp
  planner_visible: true
- name: pick_object
  implementation: lekiwi_handeye_realsense_grasp
  planner_visible: true
- name: place_in_container
  implementation: lekiwi_handeye_realsense_grasp
  planner_visible: true
- name: recover_safe_pose
  implementation: lekiwi_handeye_realsense_grasp
  planner_visible: true
- name: imitate_human_motion
  implementation: lekiwi_handeye_realsense_grasp_lidar
  planner_visible: true
- name: recover_zero_pose
  implementation: lekiwi_handeye_realsense_grasp
  planner_visible: true
- name: dance_basic
  implementation: so101_arm_v1
  planner_visible: true
- name: greet_observe_raise
  implementation: so101_arm_v1
  planner_visible: true
- name: happy_spin_upright
  implementation: so101_arm_v1
  planner_visible: true
- name: nod_yes
  implementation: so101_arm_v1
  planner_visible: true
- name: rotate_gripper_ccw
  implementation: so101_arm_v1
  planner_visible: true
- name: rotate_gripper_cw
  implementation: so101_arm_v1
  planner_visible: true
- name: shake_no
  implementation: so101_arm_v1
  planner_visible: true
- name: wave_hello
  implementation: so101_arm_v1
  planner_visible: true
- name: nav_abs_coordinate
  implementation: lekiwi_navigation_v2
  planner_visible: true
- name: nav_straight
  implementation: lekiwi_navigation_v2
  planner_visible: true
- name: nav_turn
  implementation: lekiwi_navigation_v2
  planner_visible: true
- name: sound_following
  implementation: lekiwi_handeye_realsense_grasp_lidar
  planner_visible: true
