schema_version: 1
name: lekiwi_lidar
robot_name: lekiwi_lidar
enabled_skills:
- name: nav_abs_coordinate
  implementation: lekiwi_navigation_v2
  planner_visible: true
- name: nav_straight
  implementation: lekiwi_navigation_v2
  planner_visible: true
- name: nav_turn
  implementation: lekiwi_navigation_v2
  planner_visible: true
