<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>torch_models</name>
  <version>0.1.0</version>
  <description>Self-developed PyTorch models without ROS runtime dependencies.</description>
  <maintainer email="haoyida@huawei.com">yidahao</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
