"""Hermes ``post_llm_call`` bridge to the IB-Robot TTS services."""

from __future__ import annotations

import fcntl
import io
import json
import os
import re
import sys
import tempfile
import unicodedata
import wave
from datetime import datetime
from pathlib import Path
from typing import Any

_LOG_PATH = Path(os.environ.get("IBROBOT_HERMES_TTS_LOG", "/tmp/hermes-speak.log"))
_MAX_LOG_BYTES = 256 * 1024
# Fallbacks used only when the wrapper generated by hermes-robot-configure did not
# inject the corresponding env var (e.g. ad-hoc `python3 -m` invocation during
# development). Production runs source the wrapper, which binds these values from
# robot_config SSOT (voice_tts.synthesis_timeout_sec / playback_timeout_sec).
_DEFAULT_SYNTHESIS_TIMEOUT_SEC = 90.0
_DEFAULT_PLAYBACK_TIMEOUT_SEC = 300.0
_PLAYBACK_LOCK_PATH = Path(os.environ.get("IBROBOT_TTS_PLAYBACK_LOCK", "/tmp/ibrobot-tts-playback.lock"))


class SpeechHookError(RuntimeError):
    """Stable hook failure surfaced to Hermes stderr and the hook log."""


def _log(message: str) -> None:
    try:
        if _LOG_PATH.exists() and _LOG_PATH.stat().st_size > _MAX_LOG_BYTES:
            _LOG_PATH.replace(_LOG_PATH.with_suffix(_LOG_PATH.suffix + ".1"))
        timestamp = datetime.now().astimezone().isoformat(timespec="seconds")
        with _LOG_PATH.open("a", encoding="utf-8") as stream:
            stream.write(f"{timestamp} {message}\n")
    except OSError:
        pass


def extract_response(payload: dict[str, Any]) -> str:
    """Return the final assistant response from a Hermes hook payload."""
    extra = payload.get("extra")
    if isinstance(extra, dict):
        for key in ("assistant_response", "response", "output", "text"):
            value = extra.get(key)
            if isinstance(value, str) and value.strip():
                return value.strip()
    for key in ("assistant_response", "response", "output", "text", "content"):
        value = payload.get(key)
        if isinstance(value, str) and value.strip():
            return value.strip()
    return ""


_ASCII_LETTER_RUN = re.compile(r"[A-Za-z]+")
_LONG_DIGIT_RUN = re.compile(r"\d{7,}")


def sanitize_for_tts(text: str) -> str:
    """Strip English letter runs the ZipVoice Chinese frontend cannot speak.

    Hermes responses routinely contain English (robot names, acronyms, code
    tokens). The 310P/ONNX ZipVoice frontend rejects ASCII letters, so those
    runs are removed before synthesis; Chinese, digits, and punctuation are
    preserved and the service-side segmenter inserts pauses as needed.
    """
    normalized = unicodedata.normalize("NFKC", text)
    normalized = _ASCII_LETTER_RUN.sub("", normalized)
    return _LONG_DIGIT_RUN.sub("", normalized)


def _positive_float_env(name: str, default: float) -> float:
    raw = os.environ.get(name, "").strip()
    if not raw:
        return default
    try:
        value = float(raw)
    except ValueError as exc:
        raise SpeechHookError(f"{name} must be a number") from exc
    if value <= 0.0:
        raise SpeechHookError(f"{name} must be positive")
    return value


def _wait_for_future(node, future, timeout_sec: float, operation: str):
    import rclpy

    rclpy.spin_until_future_complete(node, future, timeout_sec=timeout_sec)
    if not future.done():
        raise SpeechHookError(f"{operation} timed out after {timeout_sec:g} seconds")
    exception = future.exception()
    if exception is not None:
        raise SpeechHookError(f"{operation} service failed: {exception}")
    response = future.result()
    if response is None:
        raise SpeechHookError(f"{operation} returned no response")
    return response


def _wav_duration_sec(audio_data: bytes) -> float:
    if len(audio_data) < 12 or audio_data[:4] != b"RIFF" or audio_data[8:12] != b"WAVE":
        raise SpeechHookError("speech synthesis returned invalid WAV data")
    try:
        with wave.open(io.BytesIO(audio_data), "rb") as stream:
            frame_rate = stream.getframerate()
            if frame_rate <= 0:
                raise SpeechHookError("speech synthesis returned WAV data with an invalid frame rate")
            return stream.getnframes() / frame_rate
    except (EOFError, wave.Error) as exc:
        raise SpeechHookError(f"speech synthesis returned invalid WAV data: {exc}") from exc


def _write_wav(audio_data: bytes) -> Path:
    _wav_duration_sec(audio_data)
    descriptor, raw_path = tempfile.mkstemp(prefix="ibrobot-hermes-", suffix=".wav")
    path = Path(raw_path)
    try:
        with os.fdopen(descriptor, "wb") as stream:
            stream.write(audio_data)
    except Exception:
        path.unlink(missing_ok=True)
        raise
    return path


def speak(text: str, *, session_id: str = "") -> None:
    """Synthesize and synchronously play one extracted response."""
    import rclpy
    from rclpy.node import Node

    from ibrobot_msgs.srv import PlayAudioFile, SynthesizeSpeech

    synthesis_service = os.environ.get("IBROBOT_TTS_SYNTHESIS_SERVICE", "/voice_tts/synthesize")
    playback_service = os.environ.get("IBROBOT_TTS_PLAYBACK_SERVICE", "/voice_tts/play")
    synthesis_timeout = _positive_float_env("IBROBOT_TTS_SYNTHESIS_TIMEOUT_SEC", _DEFAULT_SYNTHESIS_TIMEOUT_SEC)
    playback_cap = _positive_float_env("IBROBOT_TTS_PLAYBACK_TIMEOUT_SEC", _DEFAULT_PLAYBACK_TIMEOUT_SEC)

    rclpy.init()
    node = Node(f"hermes_speak_{os.getpid()}")
    try:
        synthesize = node.create_client(SynthesizeSpeech, synthesis_service)
        playback = node.create_client(PlayAudioFile, playback_service)
        if not synthesize.wait_for_service(timeout_sec=10.0):
            raise SpeechHookError(f"{synthesis_service} is unavailable")
        if not playback.wait_for_service(timeout_sec=10.0):
            raise SpeechHookError(f"{playback_service} is unavailable")

        request = SynthesizeSpeech.Request()
        request.text = text
        result = _wait_for_future(node, synthesize.call_async(request), synthesis_timeout, "speech synthesis")
        if not result.success:
            raise SpeechHookError(f"speech synthesis failed [{result.error_code}]: {result.message}")
        if not result.audio_segments:
            raise SpeechHookError("speech synthesis returned no audio segments")
        _log(f"SYNTHESIZED session={session_id} segments={len(result.audio_segments)}")

        with _PLAYBACK_LOCK_PATH.open("a+") as playback_lock:
            fcntl.flock(playback_lock.fileno(), fcntl.LOCK_EX)
            for segment in result.audio_segments:
                audio_data = bytes(segment.audio_data)
                duration_sec = _wav_duration_sec(audio_data)
                path = _write_wav(audio_data)
                try:
                    play_request = PlayAudioFile.Request()
                    play_request.file_path = str(path)
                    playback_timeout = min(playback_cap, max(30.0, duration_sec + 15.0))
                    played = _wait_for_future(
                        node,
                        playback.call_async(play_request),
                        playback_timeout,
                        "audio playback",
                    )
                    if not played.success:
                        raise SpeechHookError(f"audio playback failed [{played.error_code}]: {played.message}")
                finally:
                    path.unlink(missing_ok=True)
            fcntl.flock(playback_lock.fileno(), fcntl.LOCK_UN)
        _log(f"PLAYED session={session_id} segments={len(result.audio_segments)}")
    finally:
        node.destroy_node()
        rclpy.try_shutdown()


def main() -> int:
    """Read one Hermes hook payload from stdin and play its final response."""
    raw = sys.stdin.read()
    if not raw.strip():
        return 0
    try:
        payload = json.loads(raw)
        if not isinstance(payload, dict):
            raise SpeechHookError("hook payload must be a JSON object")
        text = extract_response(payload)
        if not text:
            return 0
        session_id = str(payload.get("session_id", ""))
        sanitized = sanitize_for_tts(text)
        if not sanitized.strip():
            _log(f"SKIP session={session_id} reason=no_speakable_text chars={len(text)}")
            return 0
        _log(f"START session={session_id} chars={len(text)} speakable={len(sanitized)}")
        speak(sanitized, session_id=session_id)
    except (json.JSONDecodeError, ImportError, OSError, SpeechHookError) as exc:
        _log(f"ERROR {type(exc).__name__}: {exc}")
        print(str(exc), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
