"""Named inference pipeline composition, lifecycle, routing, and diagnostics."""

from inference_service.pipeline.errors import (
    PipelineCanceledError,
    PipelineConfigurationError,
    PipelineError,
    PipelineLifecycleError,
    PipelineManagerError,
    PipelineNotFoundError,
    PipelineNotReadyError,
    PipelineTimeoutError,
    PipelineTransitionError,
    PipelineValidationError,
)
from inference_service.pipeline.executor import SequentialModelExecutor
from inference_service.pipeline.factory import (
    create_inference_pipeline,
    create_pipeline_manager,
    register_policy_session_builders,
)
from inference_service.pipeline.manager import InferencePipelineManager
from inference_service.pipeline.pi05 import PI05Topology, PI05TopologyError, create_pi05_executor, derive_pi05_topology
from inference_service.pipeline.runtime import InferencePipeline, Postprocessor, Processor
from inference_service.pipeline.runtime_core import (
    ExecutionControl,
    ExecutionError,
    ModelExecutor,
    PipelineRuntimeDiagnostics,
    StageFrame,
)
from inference_service.pipeline.smolvla import (
    SmolVLAEmbeddingWeights,
    SmolVLAFamilyResource,
    SmolVLATopology,
    SmolVLATopologyError,
    create_smolvla_executor,
    derive_smolvla_topology,
    load_smolvla_embedding_weights,
    load_smolvla_policy_config,
    validate_smolvla_plan,
)
from inference_service.pipeline.staged_executor import (
    StagedModelExecutor,
    StagedScheduling,
    VisualFrameSupersededError,
)
from inference_service.pipeline.stages import (
    DirectIterationStateAdapter,
    EulerIterationStateAdapter,
    HostComputeStage,
    HostRoleStage,
    InferenceStage,
    IterationStateAdapter,
    IterationStep,
    IterativeStage,
    ModelResultAdapter,
    ModelStage,
    PostprocessStage,
    PreprocessStage,
    ResultAdapter,
)
from inference_service.pipeline.state import PipelineState, PipelineStateMachine
from inference_service.pipeline.types import PipelineDiagnostics, PipelineResult
from inference_service.pipeline.validation import ActionValidation, validate_action_output

__all__ = [
    "ActionValidation",
    "DirectIterationStateAdapter",
    "ExecutionControl",
    "ExecutionError",
    "EulerIterationStateAdapter",
    "HostComputeStage",
    "HostRoleStage",
    "InferencePipeline",
    "InferencePipelineManager",
    "InferenceStage",
    "IterationStateAdapter",
    "IterationStep",
    "IterativeStage",
    "ModelExecutor",
    "ModelResultAdapter",
    "ModelStage",
    "PipelineConfigurationError",
    "PipelineCanceledError",
    "PipelineDiagnostics",
    "PipelineError",
    "PipelineLifecycleError",
    "PipelineManagerError",
    "PipelineNotFoundError",
    "PipelineNotReadyError",
    "PipelineResult",
    "PipelineRuntimeDiagnostics",
    "PipelineState",
    "PipelineStateMachine",
    "PipelineTimeoutError",
    "PI05Topology",
    "PI05TopologyError",
    "PipelineTransitionError",
    "PipelineValidationError",
    "SequentialModelExecutor",
    "SmolVLAEmbeddingWeights",
    "SmolVLAFamilyResource",
    "SmolVLATopology",
    "SmolVLATopologyError",
    "Postprocessor",
    "PostprocessStage",
    "PreprocessStage",
    "Processor",
    "ResultAdapter",
    "StageFrame",
    "StagedModelExecutor",
    "StagedScheduling",
    "VisualFrameSupersededError",
    "validate_action_output",
    "create_inference_pipeline",
    "create_pi05_executor",
    "create_pipeline_manager",
    "register_policy_session_builders",
    "create_smolvla_executor",
    "derive_pi05_topology",
    "derive_smolvla_topology",
    "load_smolvla_embedding_weights",
    "load_smolvla_policy_config",
    "validate_smolvla_plan",
]
